colors: {course_name: blue, high_grade: on_green, low_grade: on_red, medium_grade: on_yellow}
host: ps.fccps.org
ignored_periods: [HR, DA, NT]
ignored_marking_periods: [M1, M2, V1]
remove_empty_marking_periods: true
remove_redundant_semester: true
show_last_week_attendance: false
show_this_week_attendance: true
show_attendance_totals: false
thresholds: {high: 95, medium: 90}
