#!/bin/bash
for fgbg in 38 48; do # Switch between foreground and background
    for color in {0..255}; do # Iterate through colors
        # Display color
        printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
        # Display 6 colors/line
        if [[ $((($color + 1) % 6)) == 4 ]]; then
            echo
        fi
    done
    echo
done
