#!/bin/python3
import sys

if len(sys.argv) > 1:
    param = sys.argv[0]
    if param.isdigit():
        print(chr(int(param)))
    else:
        print(ord(param))
else:
    for x in range(32,127):
        print("%s | %c" % (str(x).ljust(3), chr(x)))
