#!/usr/bin/env python3

import xml.etree.ElementTree as etree

tree = etree.parse('/Library/Application Support/JAMF/.blacklist.xml')
root = tree.getroot()

for item in root:
    print('{name} / {process}'.format(name=item[1].text,
                                      process=item[2].text))
