#!/bin/bash

# Host a local SSH proxy

printf "Changing proxy settings... "
ssh root@localhost -t "networksetup -setsocksfirewallproxy Wi-Fi 'localhost' 2114 && networksetup -setsocksfirewallproxystate Wi-Fi on" 2> /dev/null
echo "settings changed successfully."

echo "Launching SSH proxy... (Press Ctrl+C when done)"
ssh -ND 2114 juno
echo; echo "Proxy terminated."

printf "Resetting settings... "
ssh root@localhost -t "networksetup -setsocksfirewallproxy Wi-Fi '' '' && networksetup -setsocksfirewallproxystate Wi-Fi off" 2> /dev/null
echo "settings reset. Goodbye!"
