#!/usr/bin/env bash

mkdir -p $HOME/Desktop/sget

timestamp=`date +%s`
cmd="curl -L $1 > ~/sget/$timestamp"
ssh -t home $cmd

scp -r home:~/sget/$timestamp $HOME/Desktop/sget/$timestamp

open $HOME/Desktop/sget/$timestamp
