#!/usr/bin/env bash

mkdir -p $HOME/Desktop/sget

timestamp=`date +%s`
ssh -t home "mkdir -p ~/sget; curl -L $1 > ~/sget/$timestamp"

scp -r home:~/sget/$timestamp $HOME/Desktop/sget/$timestamp

open $HOME/Desktop/sget/$timestamp
