#!/usr/bin/env osascript
tell application "Spotify"
    if it is running then
        if player state is playing
            set status_icon to ">"
        else
            set status_icon to "||"
        end if
        set track_name to name of current track
        set artist_name to artist of current track

        status_icon & " " & artist_name & " - " & track_name
    end if
end tell

